# -*- coding: utf-8 -*-
"""Actividad N°6- Cuenta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFo2Kygwxx_r5OAFu_JVkBaifkCdYWVr
"""

#Crea una clase llamada Cuenta que tendrá los siguientes atributos: titular (que es una persona) y cantidad (puede tener decimales).
# El titular será obligatorio y la cantidad es opcional. Construye los siguientes métodos para la clase: 

#Un constructor.
#mostrar(): Muestra los datos de la cuenta. 
#ingresar(cantidad): se ingresa una cantidad a la cuenta, si la cantidad introducida es negativa, no se hará nada. 
#retirar(cantidad): se retira una cantidad a la cuenta. La cuenta puede estar en números rojos

class Cuenta():
  def __init__(self, titular, cantidad=0):
    self.titular=titular
    self.cantidad=cantidad
  def ingresar(self,cantidad):
    print(f"Se ingresa una cantidad de:{cantidad}")
  def retirar(self,cantidad):
    print(f"Se retira la cantidad de:{cantidad}")

persona= Cuenta("Natalia")
print(f"El nombre del titular de la cuenta es:{persona.titular}")
persona.ingresar(5000)
persona.retirar(2000)